### ISSUE TITLE
stacktrace in d971eda

### ISSUE THREAD

**Issue by SmoothieAq** [ncsaba/idea-openscad#42]
I have seen a stacktrace like the following a couple of time in the "IDE Fatal Errors" popup:

```
java.lang.StackOverflowError
	at java.base/java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryAcquire(ReentrantReadWriteLock.java:407)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1239)
	at java.base/java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:959)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.handleError(FSRecords.java:518)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.access$000(FSRecords.java:155)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.readAndHandleErrors(FSRecords.java:959)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.findFileById(FSRecords.java:1132)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:1237)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileByIdIfCached(PersistentFSImpl.java:1242)
	at com.intellij.util.indexing.IndexInfrastructure.findFileByIdIfCached(IndexInfrastructure.java:106)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$processValuesInScope$14(FileBasedIndexImpl.java:961)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$processValueIterator$15(FileBasedIndexImpl.java:985)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$null$11(FileBasedIndexImpl.java:910)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:242)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$processExceptions$12(FileBasedIndexImpl.java:910)
	at com.intellij.util.indexing.IndexAccessValidator.validate(IndexAccessValidator.java:43)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:910)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValueIterator(FileBasedIndexImpl.java:984)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:955)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:852)
	at com.intellij.psi.search.FileNameIndexServiceImpl.getVirtualFilesByName(FileNameIndexServiceImpl.java:27)
	at com.intellij.psi.search.FilenameIndex.processFilesByName(FilenameIndex.java:87)
	at com.intellij.psi.search.FilenameIndex.processFilesByName(FilenameIndex.java:74)
	at com.intellij.psi.search.FilenameIndex.getFilesByName(FilenameIndex.java:145)
	at com.intellij.psi.search.FilenameIndex.getFilesByName(FilenameIndex.java:65)
	at com.javampire.openscad.references.OpenSCADResolver.findFilesByRelativePath(OpenSCADResolver.java:35)
	at com.javampire.openscad.references.OpenSCADResolver.findModuleContentFile(OpenSCADResolver.java:18)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:186)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
	at com.javampire.openscad.completion.OpenSCADCompletionContributor.getLocalLibrariesModulesAndFunctions(OpenSCADCompletionContributor.java:197)
 
 ...
```

I don'w know what I was doing when it happend, but I will look out for it.

**Comment by pavelchuchma** [comment]
Reproduced this issue many times. The result is that Rider freezes forever. It is caused by a cyclic file includes (by 'use <....>')

Workaround is to refactor include graph to remove cycles. This is doable for new projects, but it is very hard for maintenance of existing projects.

Anyway, it would be very nice to have this issue fixed because include cycles are legal in OpenSCAD.

**Comment by ldenisey** [comment]
Thank you @pavelchuchma for your guidance, a fix is coming.
