### ISSUE TITLE
Error when running Reformat Code in IntelliJ

### ISSUE THREAD

**Issue by chrisl8** [ncsaba/idea-openscad#61]
I am getting this error whenever I call  Reformat Code in IntelliJ on any .scad file, even an empty one:

```
java.lang.IllegalStateException: @NotNull method com/intellij/psi/codeStyle/CommonCodeStyleSettings.getRootSettings must not return null
	at com.intellij.psi.codeStyle.CommonCodeStyleSettings.$$$reportNull$$$0(CommonCodeStyleSettings.java)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettings.getRootSettings(CommonCodeStyleSettings.java:98)
	at com.javampire.openscad.formatter.OpenSCADFormattingModelBuilder.createSpacingBuilder(OpenSCADFormattingModelBuilder.java:40)
	at com.javampire.openscad.formatter.OpenSCADFormattingModelBuilder.createModel(OpenSCADFormattingModelBuilder.java:33)
	at com.intellij.formatting.FormattingModelBuilder.createModel(FormattingModelBuilder.java:74)
	at com.intellij.formatting.FormattingModelBuilder.createModel(FormattingModelBuilder.java:63)
	at com.intellij.formatting.FormattingModelBuilder.createModel(FormattingModelBuilder.java:36)
	at com.intellij.psi.codeStyle.autodetect.IndentOptionsDetectorImpl.calcLineIndentInfo(IndentOptionsDetectorImpl.java:85)
	at com.intellij.psi.codeStyle.autodetect.IndentOptionsDetectorImpl.getIndentOptionsAdjuster(IndentOptionsDetectorImpl.java:52)
	at com.intellij.psi.codeStyle.DetectAndAdjustIndentOptionsTask.calcIndentAdjuster(DetectAndAdjustIndentOptionsTask.java:67)
	at com.intellij.psi.codeStyle.DetectAndAdjustIndentOptionsTask.lambda$scheduleInBackgroundForCommittedDocument$1(DetectAndAdjustIndentOptionsTask.java:104)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:59)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.withTimeout(ProgressIndicatorUtils.java:306)
	at com.intellij.psi.codeStyle.DetectAndAdjustIndentOptionsTask.lambda$scheduleInBackgroundForCommittedDocument$2(DetectAndAdjustIndentOptionsTask.java:103)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:113)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:59)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

IntelliJ 2020.3.2
203.7148.57

Please let me know what other data I can provide to help resolve this.

**Comment by ldenisey** [comment]
Hello,
I am not able to reproduce this behavior.
What version of plugin are you using ?
Is OpenSCAD executable well defined in Preferences -> Lanaguages & Frameworks -> OpenSCAD Language ?
Do you see the OpenSCAD code style in Preferences ->Editor -> Code Style -> OpenSCAD ?

I tried some refactorisation in #65. Can you test this PR  and let me know if it works better for you ?

**Comment by chrisl8** [comment]
Sorry for the delay. This was in Ubuntu, where it was not working.

I've been working exclusively in Windows lately and it works fine in Windows.

**Comment by ldenisey** [comment]
I was not able to reproduce on Ubuntu. Might come from an installation issue.

**Comment by chrisl8** [comment]
Thank you very much for looking into this! I was worried that this code was abandoned and I was out of luck, but clearly you are keeping up with this.

I agree that I must have had a user setup error. I really appreciate that you took the time to respond.

I'm going to close this, but if you still want me to test #65 tag me by name and I'll test it for you.
